// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Boobs.Core;
//
//    var boobsDto = BoobsDto.FromJson(jsonString);

namespace Boobs.Core
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BoobsDto
    {
        [JsonProperty("model")]
        public string Model { get; set; }

        [JsonProperty("preview")]
        public string Preview { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("rank")]
        public long Rank { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }
    }

    public partial class BoobsDto
    {
        public static BoobsDto[] FromJson(string json) => JsonConvert.DeserializeObject<BoobsDto[]>(json, Boobs.Core.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BoobsDto[] self) => JsonConvert.SerializeObject(self, Boobs.Core.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
